name: secure_messenger
description: Application de messagerie sécurisée pour réseau local.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  provider: ^6.1.1
  file_picker: ^9.0.1
  image_picker: ^1.0.7
  path: ^1.8.3
  uuid: ^4.2.2
  intl: ^0.20.2
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  connectivity_plus: ^6.1.3
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  test: ^1.24.9

flutter:
  uses-material-design: true
